baseURL: "https://ubccsss.org/"
languageCode: "en-ca"
title: UBC CSSS
theme: hugo-bootstrap-5

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: -140
    - identifier: volunteer
      name: Volunteer
      url: /volunteer/
      weight: -130
    - identifier: cube
      name: The Cube
      url: /cube/
      weight: -120
    - identifier: learn
      name: Services
      url: /services/
      weight: -110
    - identifier: clubs
      name: Clubs
      url: /about/clubs/
      weight: -100
    - identifier: contact
      name: Contact
      url: /contact/
      weight: -90

# Get date from filename, Jekyll-style.
frontmatter:
  date:
    - ":filename"
    - ":default"

permalinks:
  posts: /:section/:year/:month/:day/:slug/
  events: /:section/:year/:month/:day/:slug/

paginate: 5

copyright: Â© 2019-2021

params:
  _merge: deep
  github:
    repo: ubccsss/ubccsss.org
    branch: master
  # Default values for event `location.address`
  default_location_address:
    addressLocality: Vancouver
    addressRegion: BC
    addressCountry: CA
  mainSections:
    - events
    - posts
  truncate: false
  header:
    colorScheme: dark
  footer:
    colorScheme: dark

markup:
  goldmark:
    renderer:
      # Allow HTML inside markdown
      unsafe: true
