main:
  - identifier: about
    name: About
    url: /about/
    weight: -140
  - identifier: partners
    name: Partners
    url: /about/partners
    weight: -130
  - identifier: cube
    name: The Cube
    url: /cube/
    weight: -120
  - identifier: learn
    name: Services
    url: /services/
    weight: -110
  - identifier: courses
    name: Course Reviews
    url: /services/courses/
    weight: -100
  - identifier: tcf
    name: Technical Career Fair
    url: /tcf/
    weight: -80
  - identifier: csrc
    name: Research Conference
    url: /csrc/
    weight: -70
  - identifier: contact
    name: Contact
    url: /contact/
    weight: -50
